# Add 'repo' label to any root file changes
octoweek:
- "*"

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
documentation:
- any: ["*.md"]

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
- any: ["*.js", "*.css", "*.html"]
